### ISSUE TITLE
Seems to be not working with latest Unity with GUI Streaming

### ISSUE THREAD

**Issue by mashuk999** [Dhyeythumar/ML-Agents-with-Google-Colab#1]
What is the Issue:
It always shows this message
`File "/content/ml-agents/ml-agents/mlagents/trainers/subprocess_env_manager.py", line 98, in recv
    raise env_exception
mlagents_envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
	 The environment does not need user interaction to launch
	 The Agents' Behavior Parameters > Behavior Type is set to "Default"
	 The environment and the Python interface have compatible versions.`

Is it working on Local Machine:
I am able to train on my Local Windows machine with the editor. For google colab, I made a Linux Build as you mentioned and tried to train.

**Comment by mashuk999** [comment]
Here's the Build I am trying to train
[https://github.com/mashuk999/Sticky-Guys-Linux-AI-Train/tree/Linux-Build](url)

**Comment by dhyeythumar** [comment]
Can you tell me which Medium article you referred because there are 2 **(one to train ML-Agents without streaming & other with live streaming)**

Here are the following:
- [Training ML-Agents with Google Colab](https://dhyeythumar.medium.com/training-ml-agents-with-google-colab-cb166c3dca46)
- [Training ML-Agents with Google Colab (& Live Streaming to Twitch)](https://dhyeythumar.medium.com/training-ml-agents-with-google-colab-live-streaming-to-twitch-5324a8dfa8ef)

**The first article points to this repo which contains the example colab notebook (without streaming). So if you want to stream then refer to the second article.**

**Comment by mashuk999** [comment]
Thanks for replying super fast. You are awesome. 
I followed your Article with Twitch Streaming one.
Here's my Notebook : (https://colab.research.google.com/drive/1tjX5aAwOSS-E8rkJ4bdLYmVNeefDwqKf?usp=sharing)
(Twitch profile URL : (https://www.twitch.tv/wlserver1))
(I have all the credentials in the colab. It's just a test account)

I am trying to train Unity Humming Bird Project ((https://github.com/gunjanmimo/Hummingbirds-Unity-ML))

With SubProcess It ends within minutes so i tested it with normal command. 
It just not able to communicate with the project environment i guess.

**Comment by dhyeythumar** [comment]
Is the environment build in server/headless mode? (this one - https://github.com/mashuk999/Sticky-Guys-Linux-AI-Train)

If its not in server/headless mode then to run the env directly you have to use the `--no-graphics`  flag:
```
!mlagents-learn --run-id=SG006 --env="Sticky-Guys-Linux-AI-Train/hb.x86_64" --no-graphics
```

And one more thing I noticed is that you are not using GPU instance of the colab & without this it won't work.
I will test the notebook & update it over here.

**Comment by dhyeythumar** [comment]
The environment works & video is streamed (check the twitch channel) for few minutes & after that env escapes with the following error:
```
[WARNING] Environment timed out shutting down. Killing...
Traceback (most recent call last):
  File "/usr/local/bin/mlagents-learn", line 33, in <module>
    sys.exit(load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')())
  File "/content/ml-agents/ml-agents/mlagents/trainers/learn.py", line 250, in main
    run_cli(parse_command_line())
  File "/content/ml-agents/ml-agents/mlagents/trainers/learn.py", line 246, in run_cli
    run_training(run_seed, options)
  File "/content/ml-agents/ml-agents/mlagents/trainers/learn.py", line 125, in run_training
    tc.start_learning(env_manager)
  File "/content/ml-agents/ml-agents-envs/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/content/ml-agents/ml-agents/mlagents/trainers/trainer_controller.py", line 173, in start_learning
    self._reset_env(env_manager)
  File "/content/ml-agents/ml-agents-envs/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/content/ml-agents/ml-agents/mlagents/trainers/trainer_controller.py", line 105, in _reset_env
    env_manager.reset(config=new_config)
  File "/content/ml-agents/ml-agents/mlagents/trainers/env_manager.py", line 68, in reset
    self.first_step_infos = self._reset_env(config)
  File "/content/ml-agents/ml-agents/mlagents/trainers/subprocess_env_manager.py", line 333, in _reset_env
    ew.previous_step = EnvironmentStep(ew.recv().payload, ew.worker_id, {}, {})
  File "/content/ml-agents/ml-agents/mlagents/trainers/subprocess_env_manager.py", line 98, in recv
    raise env_exception
mlagents_envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
	 The environment does not need user interaction to launch
	 The Agents' Behavior Parameters > Behavior Type is set to "Default"
	 The environment and the Python interface have compatible versions.
```

So now I am confused here because for few minutes env is working & after that it gives the above error.

**Comment by mashuk999** [comment]
Yeah, It is happening with me also.
Initially I thought it could be the problem of project but i tried it on my local machine and it is working on windows. 
Also launching the game on colab with `/content/Sticky-Guys-Linux-AI-Train/hb.x86_64` is working fine and player is not crashing then. I can able to see full livestream on twitch.

**Comment by mashuk999** [comment]
Your Linux Build is working fine. Maybe it is caused due to some changes in latest Unity. I will try to build on same version as you.

**Comment by dhyeythumar** [comment]
**Don't do a server/headless mode while building the project. And are you downgrading the ML-Agents?**

And actually I don't have any idea about the new versions of ML-Agents because now there are too many changes (one I spotted is that you didn't used the config.yaml as argument in CLI so is this a problem?)

Another problem might be usage of torch (cpu, cuda or cuda:0 like what to use?)

**Comment by mashuk999** [comment]
Yeah the build is without headless mode.
I am using the latest unity package and release 18 of python package.
Can you send me your Unity Project source code. I will build with the latest packages and then try to train it. That way we can narrow it down to something related to latest unity or something else

**Comment by dhyeythumar** [comment]
So to avoid any complexity I have used the simple 3DBall env (from release_1 branch) for testing the video streaming package. (uploaded here - https://github.com/dhyeythumar/mlagents-example-env)

So you can use the 3DBall env from release_18 branch for testing purpose, & I think this will be easy to debug.

**Comment by mashuk999** [comment]
Thankyou for your support. 
I just updated to preview package and it starts working.
I am closing this thread now. Thanks.
You are awesome

**Comment by mashuk999** [comment]
Also If anyway, I can help in the project do tell me. The project is awesome

**Comment by mashuk999** [comment]
Also If anyway, I can help in the project do tell me. The project is awesome
